### ISSUE TITLE
Error when trying to write a SQL database in MS Azure

### ISSUE THREAD

**Issue by ChinookPDX** [ThibTrip/pangres#25]
Hi, 

I'm trying to run the example in the wiki page (https://github.com/ThibTrip/pangres/wiki/Upsert) to write to a  SQL database in MS Azure and I get this error: 

ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'ON'. (156) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: INSERT INTO example (full_name, likes_sport, updated, size_in_meters) VALUES (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, NULL, NULL) ON CONFLICT (full_name) DO UPDATE SET likes_sport=EXCLUDED.likes_sport, updated=EXCLUDED.updated, size_in_meters=EXCLUDED.size_in_meters]
[parameters: ('John Rambo', 1, datetime.datetime(2020, 2, 1, 0, 0, tzinfo=<UTC>), 1.77, 'The Rock', 1, datetime.datetime(2020, 4, 1, 0, 0, tzinfo=<UTC>), 1.96, 'John Travolta', 0)]
(Background on this error at: http://sqlalche.me/e/13/f405)

I use this for the sqlalchemy engine (it works with other stuff I'm doing) 🥇 

quoted = quote_plus(conn)
new_con = 'mssql+pyodbc:///?odbc_connect={}'.format(quoted)
engine = create_engine(new_con, fast_executemany=True)

Any suggestions?

Thanks.

**Comment by jwcook23** [comment]
@ChinookPDX I don't believe that T-SQL/SQL-Server is supported (only PostgreSQL, SQlite and MySQL). I would also be interested in this functionality & willing to contribute.

Could use temporary tables with the merge statement.

https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15

**Comment by ChinookPDX** [comment]
@jwcook23, exactly! I've been looking at this solution for python:

https://stackoverflow.com/questions/62388767/how-to-upsert-pandas-dataframe-to-microsoft-sql-server-table

**Comment by ThibTrip** [comment]
Hello @ChinookPDX and thanks @jwcook23 !

Yes sadly the `ON CONFLICT... UPDATE/IGNORE...` that `pangres` uses does not seem to be supported as I saw in this [link](https://stackoverflow.com/questions/1197733/does-sql-server-offer-anything-like-mysqls-on-duplicate-key-update) I stumbled upon this link earlier.

On the same link there is an [answer](https://stackoverflow.com/a/30660857) that could interest you and which uses a different implementation than the [last link you provided](https://stackoverflow.com/questions/62388767/how-to-upsert-pandas-dataframe-to-microsoft-sql-server-table). The syntax used in the answer resembles a bit an `ON CONFLICT` statement (`WHEN MATCHED THEN UPDATE SET x=y`).

Sadly I would not even know how to shoehorn this into the library. I don't have knowledge of and access to Microsoft SQL and the query seems much more complicated than with other SQL flavours. Basically an additional function would be needed in the [upsert module](https://github.com/ThibTrip/pangres/blob/master/pangres/upsert.py) for Microsoft SQL.

If you manage to get the example working with Microsoft SQL I would be curious to see the code :thinking: !

**Comment by ChinookPDX** [comment]
@ThibTrip thanks! Here's my working test code:

```
import pyodbc
import pandas as pd
import sys
import sqlalchemy
from sqlalchemy import create_engine, event,MetaData, Table, Column, VARCHAR, DateTime,BigInteger,Integer,Boolean,Float, String
try:
    from urllib import quote_plus  # Python 2.X
except ImportError:
    from urllib.parse import quote_plus
import numpy as np     
import time
import numpy as np
from pangres import upsert, DocsExampleTable
import pangres


server = 'my_server'
database = 'my_db'
username = 'my_uid'
password = 'my_pwd'   
driver= '{ODBC Driver 17 for SQL Server}'


conn  = 'DRIVER='+driver+';SERVER='+server+';PORT=1433; \
DATABASE='+database+';UID='+username+';PWD='+ password + \
';Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;'

quoted = quote_plus(conn)
conn = 'mssql+pyodbc:///?odbc_connect={}'.format(quoted)
engine = create_engine(conn, fast_executemany=True)

chunk_size_ = 50000
table_name = 'students'

meta = MetaData()

if engine.dialect.has_table(engine.connect(), table_name) == False:
    students = Table(
       table_name, meta, 
       Column('id', Integer, primary_key = True), 
       Column('name', String), 
       Column('lastname', String),
    )
    meta.create_all(engine)
    with engine.begin() as conn:
  
        conn.execute(
            sqlalchemy.text(
                "SET IDENTITY_INSERT "+ table_name +" ON"
            )
        )
    
    # step 0.1 - create DataFrame to UPSERT
        df = pd.DataFrame(
            [(1, 'name1','lastname1',), (2, 'name2','lastname2')], columns=['id','name','lastname']
        )
        df.set_index('id', inplace=True)
    
        # step 1 - upload DataFrame to the table
        df.to_sql(table_name, conn, index=True, if_exists='append',
                  method=None, chunksize = chunk_size_)



with engine.begin() as conn:
   
    df2 = pd.DataFrame(
        [(1, 'name1_new','lastname1'), 
         (2, 'name2','lastname2_new'),
         (3, 'name3','lastname3'),
         (4, 'name4','lastname4')],        
        columns=['id','name','lastname'])
    df2.set_index('id', inplace=True)
    
 # step 1 - upload DataFrame to temporary table
    df2.to_sql("#temp_table", conn, index=True, if_exists="replace",
               method=None, chunksize = chunk_size_)

    conn.execute(
            sqlalchemy.text(
                "SET IDENTITY_INSERT "+ table_name +" ON"
            )
            )
    # step 2 - merge temp_table into main_table
    conn.execute(
        sqlalchemy.text("""\
            UPDATE main SET main.name = temp.name,
            main.lastname = temp.lastname
            FROM """+table_name+""" main INNER JOIN #temp_table temp
                ON main.id = temp.id
            """
        )
    )
    conn.execute(
        sqlalchemy.text("""\
            INSERT INTO """+table_name+""" (id, name, lastname) 
            SELECT id, name, lastname FROM #temp_table
            WHERE id NOT IN (SELECT id FROM """+table_name+""") 
            """
        )
    )

    # step 3 - confirm results
    result = conn.execute(sqlalchemy.text("SELECT * FROM "+table_name+" ORDER BY id")).fetchall()
    print(result)  # [(1, 'row 1 new text'), (2, 'new row 2 text')]
    
```

**Comment by ThibTrip** [comment]
Hello :wave: ! Thank you very much for posting the example code. I think it's about time I closed this issue :see_no_evil: ... Please reopen if there is anything else.
