### ISSUE TITLE
Does the data frame index have to be the same as the primary key column?

### ISSUE THREAD

**Issue by ryanmsnyder** [ThibTrip/pangres#29]
The documentation states that "the index of the DataFrame must be the primary key of the SQL table". However, when testing to see what error would be thrown if the data frame index was set to another unique column other than the primary key column, no error occurs. Am I misunderstanding?

**Comment by ThibTrip** [comment]
Hello @ryanmsnyder! Thansk for writing an issue! It's normal that it works and it seems like I forgot to update the Wiki.

Notably this explanation:

![image](https://user-images.githubusercontent.com/40694343/109500999-461eb500-7a97-11eb-82a8-d7698db6d68e.png)

Do you think it is okay like this :thinking: ?

**Comment by ryanmsnyder** [comment]
That looks good to me @ThibTrip. Thanks for your work on this.
