### ISSUE TITLE
[Question] Is there any plan for testing upsert with sqlalchemy 2.0 API?

### ISSUE THREAD

**Issue by jensqin** [ThibTrip/pangres#37]
Firstly I want to say thank you! This project is super helpful for me!

According to sqlalchemy 1.4 [documentation](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html), 
_SQLAlchemy 2.0 presents a major shift for a wide variety of key SQLAlchemy usage patterns in both the Core and ORM components._
One big change is the "autocommit" feature is deprecated since 1.4.

I ran a simple test using the future flag on engine, and upsert is not working with the engine. No errors showed up, but the table in database remains the same, which made me wonder if it is related to the "autocommit" feature. [Details](https://docs.sqlalchemy.org/en/14/core/connections.html#library-level-e-g-emulated-autocommit) here.

**Comment by ThibTrip** [comment]
Hi @jensqin ! Thanks for the issue. I had a first look into it. See branch [WIP-sqlalchemy_v2](https://github.com/ThibTrip/pangres/tree/WIP-sqlalchemy_v2).

I had the same behavior as you where no updates were made. I tried this:

```python
with engine.connect().execution_options(autocommit=True) as connection:
    result = connection.execute(...)
```

That did not work so I went for:

```python
with engine.connect() as connection:
    result = connection.execute(...)
    connection.commit()
```

I was able to pass all tests except for `test_crappy_text_insert` in module `pangres/tests/test_upsert.py`. I don't understand why it doesn't pass yet :thinking: .

There are also retrocompability problems which will require some automatic switches depending on the sqlalchemy version (that should not be a big deal I think, we had a similar situation with `v1.4`).
