### ISSUE TITLE
Upsert raises Index Error :

### ISSUE THREAD

**Issue by jv1808** [ThibTrip/pangres#38]
I'm using Python3.9 and pangres==2.3.1 
If I use my script I get this error:
("All index levels must be named!")
IndexError: All index levels must be named!

engine = create_engine("mysql+pymysql://{user}:{pw}@10.159.XX.XX/{db}"
                       .format(user='XXX_DB',
                               pw='XXXX',
                               db='Data_Test'))      
schema ='None'

        upsert(engine=engine,
        df=MATConsumptionData,
        table_name='MaterialConsumption',
        if_row_exists='ignore',
        create_schema=True,
        add_new_columns=True,
        adapt_dtype_of_empty_db_columns=True,
        chunksize=1000, 
        dtype={'ShiftDate': DATE(), 
                "ShiftID": INTEGER(),
                "OrderID": VARCHAR(30),
                "OperNum": INTEGER(),
                "EmpID": INTEGER(),
                "EmpName": VARCHAR(30),
                "EventType": VARCHAR(10),
                "ReportDate": DATE(),
                "ReportTime(Seconds)": INTEGER(),
                "ReportTime": TIME(),
                "QtyReported": FLOAT(precision=3, asdecimal=True),
                "MaterialID": VARCHAR(30),
                "MaterialDesc": VARCHAR(30),
                "InvLocation": VARCHAR(30),
                "LotNum": VARCHAR(30),
                "QtyRequired": FLOAT(precision=3, asdecimal=True),
                "QtyPer": FLOAT(precision=3, asdecimal=True),
                "QtyNominal": FLOAT(precision=3, asdecimal=True),
                "MatlUOM": VARCHAR(length=3),
                "Sequence": BigInteger()
                }) 

Whats wrong?

**Comment by ThibTrip** [comment]
Hi @jv1808 !

In a pandas DataFrame indices and columns are seperate entities. Your columns most likely all have names but it seems your index is lacking a name.

You have to set a **unique** column as the index. The index will be used to solve conflicts when updating/ignoring preexisting records. Judging by the name of your columns your index could be `ShiftID`:

```python
MATConsumptionData = MATConsumptionData.set_index('ShiftID')
```

or maybe it is a combination of (`ShiftId`, `MaterialID`)? I cannot say without seeing the table (and I am not familiar with the data anyways so I can only speculate):

```python
MATConsumptionData = MATConsumptionData.set_index(['ShiftID', 'MaterialID'])
```

In any case if you are not familiar with indices in pandas I made a gist about the [basic usage of indices](https://gist.github.com/ThibTrip/3d2719f476a43c625e270eb69fd05df8) in pandas.

Also please note that if the table already exists `pangres` will be looking for a unique or primary key in the SQL table that corresponds to the index.

**Comment by jv1808** [comment]
Thank you for the fix and the Link !!!
It seems to work. I didn't know about setting the index. I thought my MYSQL DB is doing this.

**Comment by ThibTrip** [comment]
Happy I could help :+1:. Well if the SQL table does not exist `pangres` will create a primary key automatically based on the DataFrame's index. And if the table exists `pangres` will look for a primary key or unique key that corresponds to the index.
