### ISSUE TITLE
Regarding limit of Upserting

### ISSUE THREAD

**Issue by Tikazuz** [ThibTrip/pangres#49]
Hey ThibTrip, i really love pangres that has made my life so much easier working with SQL. 

However i was wondering what are the actual limits with pangres upsert. 

Ive been trying to add 60 days of financial data into a dataframe, and im getting an error, with regards to duplicates, but when i try and remove dupes, it shows there is no dublications in my data. 

This is the error:
pangres.exceptions.DuplicateValuesInIndexException: The index must be unique since it is used as primary key.
Check duplicates using this code (assuming df  is the DataFrame you want to upsert):
>>> df.index[df.index.duplicated(keep=False)]

I must say that i will thorugly check whether its just me that have done something wrong, but it peaked my interest in what the limits are anyways. 
So i hope you can help me. 

It also says in your docs, that maximum of 1000 colums is limit, so does that include rows too? 

Best regards. 

Mathias.

**Comment by Tikazuz** [comment]
```
pangres.exceptions.DuplicateValuesInIndexException: The index must be unique since it is used as primary key.
Check duplicates using this code (assuming df  is the DataFrame you want to upsert):
>>> df.index[df.index.duplicated(keep=False)]
```

**Comment by Tikazuz** [comment]
The Error is due to exactly what the error expressed so my own fault. 

However im still interested in the question i asked :) 

Best regards.
Mathias.

**Comment by ThibTrip** [comment]
Hi @Tikazuz the idea is that when you have 1000 columns (or 32767 columns for SQlite >= 3.32.0) then one could not even insert one row without exceeding the number of parameters per SQL query. `pangres` uses one SQL parameter per "cell".

So to answer your question, rows do not count. But if you have for instance 30000 columns then you'll only be able to insert one row at a time so it'll be slow :snail: .

**Comment by Tikazuz** [comment]
Ahh in that way, i see. 

Thanks for your answer, and everything worked out with what i was trying to do:) 

Best regards. 
Mathias
