### ISSUE TITLE
Changelog (releases)

### ISSUE THREAD

**Issue by frainfreeze** [ThibTrip/pangres#58]
There is typo in the change log for [v4.0](https://github.com/ThibTrip/pangres/releases/tag/v4.0) - it lists breaking change "The first argument engine has been be renamed to con and now accepts engines and connections" however the argument `engine` was not renamed to `con` but rather to `connection`

p.s. It would be nice if the change log was (also) a document in the source tree.

**Comment by ThibTrip** [comment]
Hi @frainfreeze, thanks for your issue! What do you mean there is a typo :thinking: ?

The release `v4.0` states:

> There have been important changes in the main function pangres.upsert

and on this branch if I look at the `core` module where the [function pangres.upsert](https://github.com/ThibTrip/pangres/blob/v4.0/pangres/core.py#L21) is defined then the first argument is `con`.

As for the changelog I found a tool to generate it. However I was surprised to see that it does not have any release notes inside (should'nt the changelog have that? people don't want to have to click on the release link each time...). I quickly wrote a script to add the release notes, below is how the output looks like for the 2 last releases (of course all releases will be in the changelog this is just for demonstration purposes). Is this format okay? I would add this as "CHANGELOG.md" in the root of the repository.

# Changelog

## [v4.1](https://github.com/ThibTrip/pangres/releases/tag/v4.1) (2022-01-21)


**Release Notes**


___
**_New Features_**

* Added async support with function `pangres.aupsert` :rocket: ! Tested using `aiosqlite` for SQlite, `asyncpg` for PostgreSQL and `aiomysql` for MySQL. See documentation in dedicated wiki [page](https://github.com/ThibTrip/pangres/wiki/Aupsert)
___



[Full Changelog](https://github.com/ThibTrip/pangres/compare/v4.0.2...v4.1)

**Implemented enhancements:**

- \[FEAT\] Add `pangres.aupsert` \(async variant\) [\#55](https://github.com/ThibTrip/pangres/pull/55) ([ThibTrip](https://github.com/ThibTrip))

**Closed issues:**

- Add async support? [\#47](https://github.com/ThibTrip/pangres/issues/47)

## [v4.0.2](https://github.com/ThibTrip/pangres/releases/tag/v4.0.2) (2022-01-17)


**Release Notes**


___
This patches an important bug with MySQL. We recommend that all users upgrade to this version.

**_Bug Fixes_**

* Fixed bug where tables in MySQL where created with auto increment on the primary key (see #56)
___



[Full Changelog](https://github.com/ThibTrip/pangres/compare/v4.0.1...v4.0.2)

**Closed issues:**

- MySQL creating undesired auto incrementing primary keys [\#56](https://github.com/ThibTrip/pangres/issues/56)
- Get rid of the LooseVersion warning [\#54](https://github.com/ThibTrip/pangres/issues/54)

**Comment by frainfreeze** [comment]
you're right, it's not a typo, sorry! I was looking at [PandasSpecialEngine connection param](https://github.com/ThibTrip/pangres/blob/v4.0/pangres/engine.py#L49), coming from an [older version](https://github.com/ThibTrip/pangres/blob/38d79f596fc5e29e0be1d9f00a683b6875d558ec/pangres/helpers.py#L51) where it was named engine.

Changelog format is perfect, thank you for the consideration, and quick reply!

**Comment by ThibTrip** [comment]
Hi @frainfreeze, I have just now uploaded the changelog. Feel free to reopen if there is anything else. Also please be careful if you use `PandasSpecialEngine` because it was not meant for end users. I may change it in future versions without warning.
Although I have to say no changes are planned as of now (apart from fixing tests which is unrelated to that)...

End users are supposed to use everything that is documented in the wiki (`pangres.upsert`, `pangres.aupsert`, `pangres.fix_psycopg2_bad_cols`, ...).

**Comment by frainfreeze** [comment]
Thanks!
