### ISSUE TITLE
Add example for using a tqdm progress bar with pangres.upsert

### ISSUE THREAD

**Issue by nacho53dolt** [ThibTrip/pangres#63]
It looks like it could be possible with the yield_chunks upsert argument, but it's tough to say. Would love to be able to get a progress bar going through these upserts.

**Comment by ThibTrip** [comment]
Hi @nacho53dolt, sorry for not answering before I was not working with this library actively anymore.

I added a [demo notebook](https://github.com/ThibTrip/pangres/blob/master/demos/pangres_demo_tmq.ipynb). Unfortunately, I was not able to figure out how to use `tqdm` with `pangres.aupsert` (asynchronous variant of `pangres.upsert`). I hope you don't need it. 

Feel free to reopen this issue if there is anything else.

**Comment by nacho53dolt** [comment]
That example looks great, thanks! The filename is currently "pangres_demo_tmq.ipynb". I'm wondering if "pangres_demo_tqdm.ipynb" would be better? Does "tmq" mean something that I'm missing?

**Comment by ThibTrip** [comment]
Ah yes thank you @nacho53dolt, that was a typo. I fixed it.
