### ISSUE TITLE
Don't work with Pandas 2.0

### ISSUE THREAD

**Issue by tiokouBrice** [ThibTrip/pangres#70]
Need to adapt some function:
Exemple this line in engine.py

pandas_sql_engine = pd.io.sql.SQLDatabase(engine=connection, schema=schema)

Need to be too work with pandas>=2.0

pandas_sql_engine = pd.io.sql.SQLDatabase(conn=connection, schema=schema)

**Comment by ThibTrip** [comment]
@tiokouBrice I've merged your fix and fixed some tests due to pandas 2.0 (see PR #73 ). Now I just need to make a new version :)
