### ISSUE TITLE
Minimum viable documentation

### ISSUE THREAD

**Issue by triberichard** [ThibTrip/pangres#74]
Thank you for the excellent library!

I was initially confused by the lack of an easily accessible implementation example. This might be useful to include on the front page of the wiki:

```
pip install pangres
```
```
import pangres

df = df.set_index(index_column_name)  # required

pangres.upsert(
    con=engine,
    df=df,
    table_name=table_name,
    if_row_exists='update',
    dtype=dtype,
    chunksize=1000,
    create_table=True,
) 
```

Thanks again! 🙏

**Comment by ThibTrip** [comment]
Thanks! I made the modification. Sorry for the big delay, too much procrastination with my TODOs...
