### ISSUE TITLE
"upsert" is not exported from module "pangres" (PyrightreportPrivateImportUsage)

### ISSUE THREAD

**Issue by DeflateAwning** [ThibTrip/pangres#82]
```
"upsert" is not exported from module "pangres" Pyright[reportPrivateImportUsage](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportPrivateImportUsage)
```

I get this linting error. I think we just need to add `"upsert"` to the `__all__` list in `__init__.py`.

**Comment by ThibTrip** [comment]
Hey, I'll do some checks when I have the time. I can use VSCode for that where I have pyright installed (IIRC it's there by default).

In the meantime, could you tell me, are you importing using `*` i.e. `from pangres import *`?.

**Comment by DeflateAwning** [comment]
I was doing `import pangres` and `pangres.upsert(...)`
